spring:
  application:
    name: b-service
  output:
    ansi:
      enabled: always
#  threads:
#    virtual:
#      enabled: false
  cloud:
    aws:
      endpoint: http://localhost:4566
      region:
        static: us-west-1
      credentials:
        access-key: noop
        secret-key: noop
    stream:
      bindings:
        input-in-0:
#          destination: sqs-1
          destination: channeldestination
          content-type: application/json
#          binder: sqs
    function:
      definition: input
server:
  port: 8081

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %thread - %X{traceId} - %X{power} -%X{customerId} - %logger{36} - %msg%n"

management:
  tracing:
    baggage:
      correlation:
        fields: orderId, customerId, power
        enabled: true
      remote-fields: orderId, customerId, power
#    propagation:
#      produce: [b3,w3c]
#      consume: [b3,w3c]