server:
  port: 8081
spring:
  application:
    name: b-service
  output:
    ansi:
      enabled: always
  cloud:
    aws:
      endpoint: http://localhost:4566
      region:
        static: us-west-1
      credentials:
        access-key: noop
        secret-key: noop
    stream:
      bindings:
        ptmsqs-in-0:
          destination: sqs-1
          content-type: application/json
          binder: sqs
    function:
      definition: ptmsqs

management:
  tracing:
    baggage:
      remote-fields: email
      correlation:
        fields: email
        enabled: true


logging:
  pattern:
    console: "%d{HH:mm:ss} - %t %X{traceId} %X{spanId} %X{email} %X{power}- %msg%n"

otel:
  logs:
    exporter: none
  metrics:
    exporter: none
#  traces:
#    exporter: none
